name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1  
      
      - name: Deploy to S3
        run: |
          aws s3 sync "./BMI Calculator" s3://alinabucket-unique-16 --acl public-read --delete
          aws s3 sync "./BMI Rechner" s3://alinabucket-unique-16 --acl public-read --delete
